language: node_js
node_js:
  - '8'
sudo: false
addons:
  sauce_connect:
    username: metal-toggler
    no_ssl_bump_domains: all
  jwt:
    secure: {token}
before_install:
  - npm install
script:
- npm run checkFormat
- npm run lint
- npm run test:saucelabs